import { Navigation } from 'react-native-navigation';

import ExploreViewContainer from './containers/ExploreViewContainer';
import ExploreRefineSearchViewContainer from './containers/ExploreRefineSearchViewContainer';
import InboxViewContainer from './containers/InboxViewContainer';
import InboxTaskDetailContainer from './components/Inbox/TaskDetail';
import ThirdViewContainer from './containers/ThirdViewContainer';
import QuoteViewContainer from  './containers/QuoteViewContainer';
import TaskViewContainer from './containers/TaskViewContainer';
import SecondSectionViewContainer from './containers/SecondSectionViewContainer';
import PostDescriptionContainer from './containers/PostDescriptionViewContainer';
import PostNextViewContainer from './containers/PostNextViewContainer';
import PostViewContainer from  './containers/PostViewContainer';
import OfferSectionContainer from './containers/OfferSectionContainer';
import OfferNextViewContainer from './containers/OfferNextViewContainer';
import OfferViewContainer from './containers/OfferViewContainer';
import ScheduleSectionContainer from './containers/ScheduleSectionContainer';
import ScheduleAddTimeContainer from './containers/ScheduleAddTimeContainer';
import ScheduleEditTimeContainer from  './containers/ScheduleEditTimeContainer';
import ScheduleViewContainer from './containers/ScheduleViewContainer';
import InvoiceSectionContainer from './containers/InvoiceSectionContainer';
import InvoiceNextViewContainer from  './containers/InvoiceNextViewContainer';
import InvoiceViewContainer from './containers/InvoiceViewContainer';
import InvoiceListViewContainer from './containers/InvoiceListViewContainer';
import DisputePopup from  './components/NewInvoice/DisputePopup';
import RefundPopup from  './components/NewInvoice/RefundPopup';
import InvoiceFeedbackViewContainer from './containers/InvoiceFeedbackViewContainer';
import ResetPasswordContainer from './containers/ResetPasswordViewContainer';
import TermsAndConditionsContainer from './containers/TermsAndConditionsViewContainer';
import PrivacyPolicyContainer from './containers/PrivacyPolicyViewContainer';
import ProviderListResultContainer from './containers/ProviderListResultViewContainer';
import ReportProblemContainer from './containers/ReportProblemViewContainer';
import ReportAbout from './components/ReportProblem/ReportAbout';
import ReportDocuments from './components/ReportProblem/ReportDocuments';
import ReportReview from './components/ReportProblem/ReportReview';


const registerScreens = (store, Provider) => {
  Navigation.registerComponent('global.ExploreView', () => ExploreViewContainer, store, Provider);
  Navigation.registerComponent('global.ExploreRefineSearchView', () => ExploreRefineSearchViewContainer, store, Provider);
  Navigation.registerComponent('global.InboxView', () => InboxViewContainer, store, Provider);
  Navigation.registerComponent('global.InboxTaskDetailView', () => InboxTaskDetailContainer, store, Provider);
  Navigation.registerComponent('global.ThirdView', () => ThirdViewContainer, store, Provider);
  Navigation.registerComponent('global.QuoteView', () => QuoteViewContainer, store, Provider);
  Navigation.registerComponent('global.TaskView', () => TaskViewContainer, store, Provider);
  Navigation.registerComponent('global.SecondSection', () => SecondSectionViewContainer, store, Provider);
  Navigation.registerComponent('global.PostDescriptionView', () => PostDescriptionContainer, store, Provider);
  Navigation.registerComponent('global.PostNextView', () => PostNextViewContainer, store, Provider);
  Navigation.registerComponent('global.PostView', () => PostViewContainer, store, Provider);
  Navigation.registerComponent('global.OfferSection', () => OfferSectionContainer, store, Provider);
  Navigation.registerComponent('global.OfferNextView', () => OfferNextViewContainer, store, Provider);
  Navigation.registerComponent('global.OfferView', () => OfferViewContainer, store, Provider);
  Navigation.registerComponent('global.ScheduleSection', () => ScheduleSectionContainer, store, Provider);
  Navigation.registerComponent('global.ScheduleAddTime', () => ScheduleAddTimeContainer, store, Provider);
  Navigation.registerComponent('global.ScheduleEditTime', () => ScheduleEditTimeContainer, store, Provider);
  Navigation.registerComponent('global.ScheduleView', () => ScheduleViewContainer, store, Provider);
  Navigation.registerComponent('global.InvoiceSection', () => InvoiceSectionContainer, store, Provider);
  Navigation.registerComponent('global.InvoiceNextView', () => InvoiceNextViewContainer, store, Provider);
  Navigation.registerComponent('global.InvoiceView', () => InvoiceViewContainer, store, Provider);
  Navigation.registerComponent('global.InvoiceListView', () => InvoiceListViewContainer, store, Provider);
  Navigation.registerComponent('global.DisputePopup', () => DisputePopup, store, Provider);
  Navigation.registerComponent('global.RefundPopup', () => RefundPopup, store, Provider);
  Navigation.registerComponent('global.InvoiceFeedbackView', () => InvoiceFeedbackViewContainer, store, Provider);
  Navigation.registerComponent('global.ResetPassword', () => ResetPasswordContainer, store, Provider);
  Navigation.registerComponent('global.TermsAndConditions', () => TermsAndConditionsContainer, store, Provider);
  Navigation.registerComponent('global.PrivacyPolicy', () => PrivacyPolicyContainer, store, Provider);
  Navigation.registerComponent('global.ProviderListResult', () => ProviderListResultContainer, store, Provider);
  Navigation.registerComponent('global.ReportProblemView', () => ReportProblemContainer, store, Provider);
  Navigation.registerComponent('global.ReportAboutView', () => ReportAbout, store, Provider);
  Navigation.registerComponent('global.ReportDocumentsView', () => ReportDocuments, store, Provider);
  Navigation.registerComponent('global.ReportReviewView', () => ReportReview, store, Provider);
};

export default registerScreens;
